[package]
name = "bcnotif"
version = "0.9.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[features]
show-feed-info = []

[dependencies]
hyper       = "0.10.*"
csv         = "0.15.*"
chrono      = "0.3.*"
yaml-rust   = "0.3.*"
select      = { git = "https://github.com/utkarshkukreti/select.rs" }
error-chain = "0.9.*"

[target.'cfg(unix)'.dependencies]
notify-rust = "3.*"

[target.'cfg(windows)'.dependencies]
winapi       = "0.2.*"
user32-sys   = "0.2.*"
kernel32-sys = "0.2.*"
lazy_static  = "0.2.*"