[package]
name = "bcnotif"
version = "0.9.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[features]
print-feed-data = []

[dependencies]
error-chain = "0.11"
chrono      = "0.4"
csv         = "1.0.0-beta.4"
select      = "0.4"
reqwest     = "0.8"
yaml-rust   = "0.3"

[target.'cfg(any(unix, macos))'.dependencies]
notify-rust = "3"

[target.'cfg(windows)'.dependencies.winrt]
version = "0.3"
features = ["windows-data", "windows-ui"]