[package]
name = "bcnotif"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
dirs = "~2.0.0"
gumdrop = "~0.7.0"
notify-rust = "~3.6.0"
once_cell = "~1.3.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~1.2.0"
snafu = "~0.6.0"
toml = "~0.5.0"

[dependencies.chrono]
version = "~0.4.0"
features = [ "serde" ]

[dependencies.ctrlc]
version = "~3.1.0"
features = [ "termination" ]

[dependencies.diesel]
version = "~1.4.0"
default-features = false
features = [ "sqlite", "chrono" ]

[dependencies.reqwest]
version = "~0.10.0"
features = [ "blocking" ]

[profile.release]
lto = true
codegen-units = 1