[package]
name = "bcnotif"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
failure = "~0.1.0"
chrono = "~0.4.0"
clap = "~2.33.0"
directories = "~2.0.0"
notify-rust = "~3.6.0"
once_cell = "~1.2.0"
smallvec = "~1.1.0"
reqwest = "~0.9.0"
yaml-rust = "~0.4.0"

[profile.release]
lto = true
codegen-units = 1