[package]
name = "bcnotif"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
chrono = "~0.4.0"
clap = "~2.33.0"
dirs = "~2.0.0"
notify-rust = "~3.6.0"
once_cell = "~1.3.0"
smallvec = "~1.1.0"
snafu = "~0.6.0"
yaml-rust = "~0.4.0"

[dependencies.ctrlc]
version = "~3.1.0"
features = [ "termination" ]

[dependencies.diesel]
version = "~1.4.0"
default-features = false
features = [ "sqlite", "chrono" ]

[dependencies.reqwest]
version = "~0.10.0"
features = [ "blocking" ]

[profile.release]
lto = true
codegen-units = 1