[package]
name = "bcnotif"
version = "0.9.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[dependencies]
hyper       = "0.10.*"
regex       = "0.2.*"
lazy_static = "0.2.*"
csv         = "0.15.*"
chrono      = "0.2.*"
notify-rust = "3.*"
yaml-rust   = "0.3.*"
