[package]
name = "bcnotif"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
failure = "~0.1.0"
chrono = "~0.4.0"
clap = "~2.32.0"
csv = "~1.0.0"
directories = "~1.0.0"
hashbrown = "~0.1.0"
lazy_static = "~1.3.0"
notify-rust = "~3.5.0"
select = "~0.4.2"
smallvec = "~0.6.0"
reqwest = "~0.9.0"
yaml-rust = "~0.4.0"