[package]
name = "bcnotif"
version = "0.9.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[profile.release]
lto = true

[features]
print-feed-data = []

[dependencies]
failure     = "0.1"
chrono      = "0.4"
csv         = "1"
directories = "0.10"
lazy_static = "1"
select      = "0.4"
reqwest     = "0.8"
yaml-rust   = "0.4"

[target.'cfg(any(unix, macos))'.dependencies]
notify-rust = "3"

[target.'cfg(windows)'.dependencies.winrt]
version = "0.5"
features = ["windows-data", "windows-ui"]